### ISSUE TITLE
ImportError: No module named 'resource'

### ISSUE THREAD

**Issue by shaukat72** [RussellLuo/resource#3]
I am using resource module on windows i:e; 
import resource

But it generates an error (ImportError: No module named 'resource')
The reference link (https://docs.python.org/2/library/resource.html) says it is for UNIX only.
So what is an alternate functionality to use on Windows?

Any help would be appreciated

**Comment by RussellLuo** [comment]
@shaukat72 Sorry for replying you so late!

The actual name has been renamed to `rsrc` (see [this commit](https://github.com/RussellLuo/resource/commit/e21258166cef8c483ce9c62ad7dce782f72c0e9f)),
 since the original name is conflict with the built-in library `resource`:

```python
$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import resource
>>> resource
<module 'resource' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/resource.so'>
```
